<a href="https://colab.research.google.com/github/akarajic/CUS615/blob/main/Competition_001/InClassCompetition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

In [70]:
training_set = pd.read_csv('train 3.csv')
training_set = training_set.dropna()
training_set = training_set.drop(['id'], axis=1)
test_set = pd.read_csv('test.csv')
test_set = test_set.drop(['id'], axis=1)

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(training_set.drop('Label', axis=1), training_set['Label'], test_size=.25, random_state=42)

In [72]:
from sklearn.neighbors import KNeighborsClassifier 
KNNmodel  = KNeighborsClassifier(n_neighbors=35)   
KNNmodel.fit(X_train,Y_train)         
y_validated= KNNmodel.predict(X_test)
y_pred= KNNmodel.predict(test_set)   

In [73]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score,classification_report 
cm = confusion_matrix(Y_test, y_validated)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ac = accuracy_score(Y_test,y_validated)
ps = precision_score(Y_test, y_validated, average='macro')
rs = recall_score(Y_test, y_validated, average='macro')
f1s = f1_score(Y_test, y_validated, average='macro')
print('Confusion Matrix:')
print(cm)
print(' \n Normalized Confusion Matrix:')
print(cm_normalized)
print(' \n Accuracy Score:')
print(ac)
print(' \n Precision Score:')
print(ps)
print(' \n Recall Score:')
print(rs)
print(' \n F1-Score:')
print(f1s)
     

Confusion Matrix:
[[156  18   1]
 [ 24 123  17]
 [  1   7 149]]
 
 Normalized Confusion Matrix:
[[0.89142857 0.10285714 0.00571429]
 [0.14634146 0.75       0.10365854]
 [0.00636943 0.04458599 0.94904459]]
 
 Accuracy Score:
0.8629032258064516
 
 Precision Score:
0.8617250343273435
 
 Recall Score:
0.8634910524719442
 
 F1-Score:
0.8615397064211047


In [74]:
from sklearn.metrics import accuracy_score
import numpy as np
sample = pd.read_csv('sample_submission.csv')
sample = sample
sample['Label'] = y_pred
Label = np.array(sample['Label'])

print(sample)
sample.to_csv(r'sample.csv', index=False, header=True)

       id  Label
0       4      2
1       6      2
2      12      2
3      18      0
4      22      0
..    ...    ...
491  2465      1
492  2466      1
493  2470      0
494  2471      1
495  2477      2

[496 rows x 2 columns]


In [75]:
print(y_pred)

[2 2 2 0 0 2 2 0 0 0 1 2 1 0 2 1 1 0 0 0 2 0 1 2 1 0 0 0 0 1 2 0 2 1 1 0 1
 0 2 0 2 1 0 2 2 2 2 2 2 0 0 1 1 1 0 0 1 2 2 1 1 0 2 2 0 0 2 1 2 1 1 2 0 0
 1 2 1 2 0 0 2 2 2 2 1 2 2 2 0 2 1 1 2 0 0 1 1 2 0 2 0 0 0 1 1 2 0 0 0 2 1
 0 0 2 1 2 2 1 2 2 0 2 2 0 0 0 2 2 1 0 1 0 0 2 2 0 2 2 0 2 1 2 1 1 2 2 2 0
 0 1 2 2 0 1 0 1 2 0 1 0 0 2 2 0 1 0 0 2 0 1 1 1 1 0 2 2 1 0 2 0 1 1 0 1 2
 1 0 0 2 2 1 0 2 1 2 0 2 1 2 0 2 1 2 1 2 1 0 0 2 2 0 2 2 0 2 1 2 0 1 0 2 1
 1 1 1 2 2 1 0 2 0 0 2 0 2 1 1 2 2 0 1 0 1 2 0 0 0 1 0 2 0 2 1 2 0 0 0 2 1
 2 2 2 1 0 2 0 2 2 1 1 0 1 2 1 1 1 2 2 2 0 0 2 1 1 0 1 2 2 0 2 1 1 0 1 2 1
 1 2 1 0 2 2 1 1 0 0 0 0 2 0 1 0 0 0 1 1 0 2 1 0 0 0 0 1 1 2 2 2 0 0 1 2 0
 2 1 1 2 2 0 2 0 2 0 0 2 0 2 1 0 1 1 2 1 0 2 1 2 1 2 2 1 2 1 2 0 2 1 1 1 2
 2 2 0 0 1 0 1 2 0 2 1 1 1 1 2 1 1 0 2 0 1 1 0 0 2 2 2 1 0 1 0 0 0 1 0 2 2
 0 0 2 1 2 0 0 2 1 2 0 0 0 2 2 2 2 0 1 1 0 0 1 1 1 2 0 2 0 0 1 0 2 1 0 0 0
 1 0 0 2 0 1 0 2 0 1 2 1 0 2 0 2 0 0 0 1 2 0 1 1 1 0 0 0 0 0 0 0 0 2 2 2 0
 0 1 1 2 1 1 2 0 0 0 1 1 