<a href="https://colab.research.google.com/github/akarajic/CUS615/blob/main/ProblemSet5/Problem_set_05_ModelEvaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is part the of Dr. Christoforos Christoforou's course materials. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials or any of their derivatives without the instructor's express written consent.





## Problem Set 05: Hyperparameter Tuning and Model Selection

## Cross-validation example code
Oftentimes, we might consider one of several classification models as our predictive function, or we might want to identify the optimal set parameters for a particular classifier. For example, the KNN classifier expects the parameter `K` which indicates the number neighbors, the SVM classifier expects some hyperparameters such as the value `C`, and the `kernel` function. 

Typically, we want to select the best set of parameters for our particular model. One method for selecting such hyperparameters is `cross-validation`. 

The code below illustrates how you can use `sklearn` functions to perform `cross-validation`.

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import metrics
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold 

In [2]:
# Generate a sample Dataset. 
n_samples = 100
noisy_circles = datasets.make_circles(n_samples=n_samples, factor=.5, noise=.35)
X, y = noisy_circles

In [3]:
# Run one of the data generation cell above before executing this cell; 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

#
# Split the original dataset into Training and Testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=54, test_size=0.45, 
                                                    shuffle=True, stratify=y)

n_splits = 25       # Specify cross validation splits parameters (i.e. how many folds)
n_neighbors = 10    # Specify classifer parameters

# Generate a cross validation slplit iterator. 
cv = StratifiedKFold(n_splits=n_splits, random_state=54, shuffle=True)

# use it to keep track of the accuracy total accross all folds 
kfold_acc = 0.

for train_idx, valid_idx in cv.split(X_train, y_train):
  
  # Define the classificaiton model - KNeighborsClassifier() classifer.
  model = KNeighborsClassifier(n_neighbors=n_neighbors)

  # Train the classifier on the subset of the training data that are in the training index set current cross validation fold. 
  model.fit(X_train[train_idx],y_train[train_idx])

  # Test the classifer on the subset of the training data that are in the validation index set of the current cross validation fold.
  y_pred = model.predict(X_train[valid_idx])

  # Obtain an estimate of the accuracy of the prediciton. 
  # Here we can use any of the classifer perfomrance matrics we want. 

  acc_metric = metrics.accuracy_score(y_pred,y_train[valid_idx])
  kfold_acc += acc_metric 

# cross validation loop is complete; calcualte the average accuracy. 
kfold_acc = kfold_acc/n_splits

#
# Calculate the accuracy of the classifer on an independent test set. 
# 
 
model = KNeighborsClassifier(n_neighbors=n_neighbors)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = metrics.accuracy_score(y_pred, y_test)

print("Cross-validation Accuracy: {:.2f}".format(kfold_acc))
print("Test Accuracy: {:.2f}".format(test_acc))


Cross-validation Accuracy: 0.57
Test Accuracy: 0.64


Alternatively, we can use the `cross_val_score` to simplify the procedure as follows:

In [4]:
#
# Since cross-validation use-case is so common when assessing the performance of a classifer, sklearn library 
# has a dedicated method (i.e. the corss_val_score) that implements the entire cross-validation pipeline. 
#
# A more compact way to implement the same logic as the code above is to use a method provided by sklearn library.
 

from sklearn.model_selection import cross_val_score

#
# Split the original dataset into Training and Testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=54, test_size=0.45, 
                                                    shuffle=True, stratify=y)
# Specify the classifier. 
model = KNeighborsClassifier(n_neighbors=n_neighbors)

# Specify the corss validation parameters
cv = StratifiedKFold(n_splits=10, random_state=43, shuffle=True)

# Rum the corss-validation processing pipline 
cv_acc = cross_val_score(estimator=model,
                         X=X_train,
                         y=y_train,
                         cv=cv,
                         n_jobs=-1)

# Report results of the accuracy. 
print("Cross-validation: {:.2f}".format(np.mean(cv_acc)))

Cross-validation: 0.56


### Challenges : Cross Valudation for Hyperparameter Tuning
In this exercise, you will be working with the Pima Indians Diabetes Database database by Vincent Sigillito, which is available from the UCI database (https://archive.ics.uci.edu/ml/datasets/pima+indians+diabetes) or OpenML (https://www.openml.org/d/37).

The dataset contains information about 768 patients along with the Diabetes diagnosis. The Diabetes diagnosis is a binary label, where "tested_positive" means that a patient has diabetes and "tested_negative" means that a patient does not have diabetes.

I addition to the class label, there are 8 numeric features in the dataset, which are listed below:

- Number of times pregnant
- Plasma glucose concentration a 2 hours in an oral glucose tolerance test
- Diastolic blood pressure (mm Hg)
- Triceps skin fold thickness (mm)
- 2-Hour serum insulin (mu U/ml)
- Body mass index (weight in kg/(height in m)^2)
- Diabetes pedigree function
- Age (years)

### Download the dataset 

In [5]:
!pip install -q kaggle

In [6]:
#Upload the kaggle API key of your account 
from google.colab import files 
files.upload()
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json


In [7]:
# Download - Specify the parameters.  
kaggle_dataset_URI = "cchristoforou/practice-dataset-for-tutorials"
output_folder = "sample_data/problem_set05"
kaggle_data_file1 = "dataset_37_diabetes.csv"

In [8]:
# Download the first file from dataset - countries.csv
!kaggle datasets download $kaggle_dataset_URI --file $kaggle_data_file1 --path $output_folder

  0% 0.00/33.0k [00:00<?, ?B/s]
100% 33.0k/33.0k [00:00<00:00, 40.9MB/s]


###  Load the Dataset

Use pandas to load the dataset from the `dataset_37_diabetes.csv` CSV file located under the `sample_data/problem_set05` folder in your colab environment. Make sure you downloaded the data by executing `kaggle` command at the top of this notebook.


In [10]:
import pandas as pd
df = pd.read_csv('./sample_data/problem_set05/dataset_37_diabetes.csv')
df.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0     6   148    72    35     0  33.6  0.627   50  tested_positive
1     1    85    66    29     0  26.6  0.351   31  tested_negative
2     8   183    64     0     0  23.3  0.672   32  tested_positive
3     1    89    66    23    94  28.1  0.167   21  tested_negative
4     0   137    40    35   168  43.1  2.288   33  tested_positive

### Challenge 1 : Preprocess the class label

Convert the class label using pandas `apply` or `map` method. The mapping should be as follows:

- 'tested_positive' should be converted to 1 
- 'tested_negative' should be converted to 0

Check the documentation of the `map` method [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.map.html) and the `appy` method [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html#pandas.Series.apply)

In [11]:
import pandas as pd
df['class'] = df['class'].map({'tested_positive':1, 'tested_negative':0})
df

preg  plas  pres  skin  insu  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

### Challenge 2:  Split dataset into training and test sets

Split the dataset into 70% training and 30% test data. Perform a `stratified split` use 0 as the random seed for shuffling. You might want to check the documentatin of the `train_test_split` method of sklearn available [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).

In [12]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0, shuffle=0)

### Challenge 3:  Perform model selection on the KNN classifier

Use the above dataset to identify and evaluate the best model for this dataset when you are using the K-NN classifier. Explore different parameters for K.

1. Report which parameter K gives best result under the cross validation procedure.

2. Report the classification accuracy for the optimal parameter using cross validation for model evaluation.

3. Report the generalization performance of the optimal model on the holdout dataset.

In [13]:
# Use this cell to run cross validation and select the optimial model for KNN classifier
# (i.e. the optimal K value 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

n_splits = 25    
n_neighbors = 10   
cv = StratifiedKFold(n_splits=n_splits, random_state=0, shuffle=True)

kfold_acc = 5.

for train_idx, valid_idx in cv.split(X_train, y_train):
  model = KNeighborsClassifier(n_neighbors=n_neighbors)
  model.fit(X_train[train_idx],y_train[train_idx])
  y_pred = model.predict(X_train[valid_idx])
  acc_metric = metrics.accuracy_score(y_pred,y_train[valid_idx])
  kfold_acc += acc_metric 
kfold_acc = kfold_acc/n_splits

In [17]:
# Use this cell to calculate and report optimal model parameters and cross validation performance.  
model = KNeighborsClassifier(n_neighbors=n_neighbors)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_acc = metrics.accuracy_score(y_pred, y_test)

print("Cross-validation Accuracy: {:.2f}".format(kfold_acc))
print("Test Accuracy: {:.2f}".format(test_acc))

Cross-validation Accuracy: 0.79
Test Accuracy: 0.70


In [18]:
# Use this cell to calculate and report the generalization performance of the optimal model
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score,classification_report
cm = confusion_matrix(y_test, y_pred)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ac = accuracy_score(y_test,y_pred)
ps = precision_score(y_test, y_pred, average='macro')
rs = recall_score(y_test, y_pred, average='macro')
f1s = f1_score(y_test, y_pred, average='macro')

print('Confusion Matrix:')
print(cm)
print(' \n Normalized Confusion Matrix:')
print(cm_normalized)
print(' \n Accuracy Score:')
print(ac)
print(' \n Precision Score:')
print(ps)
print(' \n Recall Score:')
print(rs)
print(' \n F1-Score:')
print(f1s)

Confusion Matrix:
[[ 9  6]
 [ 3 12]]
 
 Normalized Confusion Matrix:
[[0.6 0.4]
 [0.2 0.8]]
 
 Accuracy Score:
0.7
 
 Precision Score:
0.7083333333333333
 
 Recall Score:
0.7
 
 F1-Score:
0.6969696969696968


##  3 Perform model selection on the SVM classifier.
Use the above dataset to identify and evaluate the best model for this dataset when you are using the SVM classifier. Explore different parameters for C, gamma and kernel.

1. Report which parameter configuration (C, gamma, kernel) gives best result under the cross validation procedure.

2. Report the classification accuracy for the optimal parameter using cross validation for model evaluation.

3. Report the generalization performance of the optimal model on the holdout dataset.

In [19]:
# Use this cell to run cross validation and select the optimial model for SVM classifier
# (i.e. the optimal C, gamma, kernal parameter configuration)

from sklearn import svm
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score,classification_report 
model  = svm.SVC(C=1.0,kernel='rbf',gamma='scale')
model.fit(X_train,y_train)
y_pred= model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ac = accuracy_score(y_test,y_pred)
ps = precision_score(y_test, y_pred, average='macro')
rs = recall_score(y_test, y_pred, average='macro')
f1s = f1_score(y_test, y_pred, average='macro')
print('Confusion Matrix:')
print(cm)
print(' \n Normalized Confusion Matrix:')
print(cm_normalized)
print(' \n Accuracy Score:')
print(ac)
print(' \n Precision Score:')
print(ps)
print(' \n Recall Score:')
print(rs)
print(' \n F1-Score:')
print(f1s)

Confusion Matrix:
[[11  4]
 [ 3 12]]
 
 Normalized Confusion Matrix:
[[0.73333333 0.26666667]
 [0.2        0.8       ]]
 
 Accuracy Score:
0.7666666666666667
 
 Precision Score:
0.7678571428571428
 
 Recall Score:
0.7666666666666666
 
 F1-Score:
0.7664071190211346


In [20]:
from sklearn import svm
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score,classification_report 
model  = svm.SVC(kernel='linear')
model.fit(X_train,y_train)
y_pred= model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ac = accuracy_score(y_test,y_pred)
ps = precision_score(y_test, y_pred, average='macro')
rs = recall_score(y_test, y_pred, average='macro')
f1s = f1_score(y_test, y_pred, average='macro')
print('Confusion Matrix:')
print(cm)
print(' \n Normalized Confusion Matrix:')
print(cm_normalized)
print(' \n Accuracy Score:')
print(ac)
print(' \n Precision Score:')
print(ps)
print(' \n Recall Score:')
print(rs)
print(' \n F1-Score:')
print(f1s)

Confusion Matrix:
[[ 5 10]
 [ 6  9]]
 
 Normalized Confusion Matrix:
[[0.33333333 0.66666667]
 [0.4        0.6       ]]
 
 Accuracy Score:
0.4666666666666667
 
 Precision Score:
0.46411483253588515
 
 Recall Score:
0.4666666666666667
 
 F1-Score:
0.45701357466063347


# Use this cell to calculate and report optimal model parameters and cross validation performance. 
The best performance came from the 'rbf' parameter, with c=1.0 and gamma= 'scale'

In [21]:
from sklearn import svm
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score,classification_report 
model  = svm.SVC(C=1.0,kernel='rbf',gamma='scale')
model.fit(X_train,y_train)
y_pred= model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
ac = accuracy_score(y_test,y_pred)
ps = precision_score(y_test, y_pred, average='macro')
rs = recall_score(y_test, y_pred, average='macro')
f1s = f1_score(y_test, y_pred, average='macro')
print('Confusion Matrix:')
print(cm)
print(' \n Normalized Confusion Matrix:')
print(cm_normalized)
print(' \n Accuracy Score:')
print(ac)
print(' \n Precision Score:')
print(ps)
print(' \n Recall Score:')
print(rs)
print(' \n F1-Score:')
print(f1s)

Confusion Matrix:
[[11  4]
 [ 3 12]]
 
 Normalized Confusion Matrix:
[[0.73333333 0.26666667]
 [0.2        0.8       ]]
 
 Accuracy Score:
0.7666666666666667
 
 Precision Score:
0.7678571428571428
 
 Recall Score:
0.7666666666666666
 
 F1-Score:
0.7664071190211346


Copyright Statement: Copyright © 2020 Christoforou. The materials provided by the instructor of this course, including this notebook, are for the use of the students enrolled in the course. Materials are presented in an educational context for personal use and study and should not be shared, distributed, disseminated or sold in print — or digitally — outside the course without permission. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials as well as any of their derivatives without the instructor's express written consent